In [6]:
import pandas as pd
import re

In [7]:
data = pd.read_csv('pek_data_2024.11.csv')

data_cleaned = data.dropna(subset=['Գործունեության տեսակ']).reset_index()

In [8]:
data_cleaned['Գործունեության տեսակ'] = data_cleaned['Գործունեության տեսակ'].apply(lambda x: re.sub(r'[^0-9.]', '', x))

In [10]:
data_cleaned = data_cleaned.loc[data_cleaned['Կարգավիճակ'].isin(['Գործող', 'Նոր գրանցված'])].reset_index(drop=True)

In [11]:
data_cleaned['Ընդանուր Գործունեության տեսակ'] = data_cleaned['Գործունեության տեսակ'].apply(lambda x: x.split('.')[0])

In [16]:
data_cleaned['Ընդանուր Գործունեության տեսակ 1'] = data_cleaned['Գործունեության տեսակ'].apply(lambda x: '.'.join(x.split('.')[:2]) if len(x.split('.')) > 1 else x)

In [17]:
data_cleaned

,index,ՀՎՀՀ,Անվանում,Կազմակերպա-իրավական տեսակ,Իրավաբանական հասցե,Գործունեության տեսակ,Գրանցման ամսաթիվ,Կարգավիճակ,Հարկման ռեժիմ,Հարկման ռեժիմում հաշվառվելու ամսաթիվ,Ընդանուր Գործունեության տեսակ,Ընդանուր Գործունեության տեսակ 1
0,837,95353264,ԳՈՀԱՐ ՆԱՎԱՍԱՐԴՅԱՆ,Նոտար,Ք.ԲԵՐԴ Նորավան 44,69.10.0,2003-01-20,Գործող,Շրջանառության հարկ վճարող,2024-01-01,69,69.10
1,840,95353221,ԱԼԲԵՐՏ ԵԳԱՆՅԱՆ,Նոտար,ՎԱՆԱՁՈՐ Սասունցիների 13ա,69.10.0,2003-01-20,Գործող,Շրջանառության հարկ վճարող,2024-01-01,69,69.10
2,841,90000007,ՍԱՐԳԻՍ ՆԱԶԱՐՅԱՆ,Անհատ ձեռնարկատեր (ԱՁ),ՈՍՏԱՆ ՄԱՅԻՍՅԱՆ Փ. 79,45.20.1,2013-03-04,Գործող,Միկրոձեռնարկատիրության սուբյեկտ,2024-01-01,45,45.20
3,847,89999178,ԱՐԹՈՒՐ ՄՈՒՐԱԴՅԱՆ,Անհատ ձեռնարկատեր (ԱՁ),ՁՈՐԱՂԲՅՈՒՐ ՀԱՂԹԱՆԱԿԻ 12,55.10.0,2016-02-18,Նոր գրանցված,ԱԱՀ վճարող,2024-01-01,55,55.10
4,848,89998915,ՀՈՎՀԱՆՆԵՍ ԴԱՎԹՅԱՆ,Անհատ ձեռնարկատեր (ԱՁ),ՏԻԳՐԱՆ ՄԵԾԻ Պ. 40 1,47.23.0,2014-03-25,Գործող,Այլ հարկ վճարող*,2024-01-01,47,47.23
...,...,...,...,...,...,...,...,...,...,...,...,...
169436,765405,34929,«ԱՌԳՈ-ՖԱՐՄ»,Սահմանափակ պատասխանատվությամբ ընկերություն (ՍՊԸ),ԱՐԱԲԿԻՐ ՍՈՒՆԴՈՒԿՅԱՆ 13 9,46.46.2,1997-03-24,Գործող,ԱԱՀ վճարող,2024-01-01,46,46.46
169437,765418,34644,ՏՈՍՊ,Սահմանափակ պատասխանատվությամբ ընկերություն (ՍՊԸ),ԵՐԵՎԱՆ Էմինի 32 չկա,68.31.0,1997-03-19,Գործող,ԱԱՀ վճարող,2024-01-01,68,68.31
169438,765422,34713,«ՄԵՅԼ- ԷՔՍՊՐԵՍ»,Սահմանափակ պատասխանատվությամբ ընկերություն (ՍՊԸ),ԵՐԵՎԱՆ Բաղրամյան 56 14,53.20.0,1997-03-20,Գործող,Շրջանառության հարկ վճարող,2024-01-01,53,53.20
169439,765428,34524,«ՎԱԼԵՄ»,Սահմանափակ պատասխանատվությամբ ընկերություն (ՍՊԸ),ԵՐԵՎԱՆ ԼԵՆԻՆԳՐԱԴՅԱՆ Փ. 23,56.10.1,2002-10-10,Գործող,ԱԱՀ վճարող,2024-01-01,56,56.10
169440,765439,34394,«ԱՐԱԲԿԻՐ 51-9»,Համատիրություն,ԵՐԵՎԱՆ ԱՐԱԲԿԻՐ 51-9 112,68.32.1,1997-03-10,Գործող,Այլ հարկ վճարող*,2024-01-01,68,68.32

In [18]:
general_activity_counts = data_cleaned.groupby('Ընդանուր Գործունեության տեսակ').size().reset_index(name='Count')

general_activity_counts = general_activity_counts.sort_values(by='Count', ascending=False)

general_activity_counts

   Ընդանուր Գործունեության տեսակ  Count
42                            47  47813
84                            96  18541
41                            46   9916
54                            62   9239
40                            45   8157
..                           ...    ...
36                            39      9
34                            37      8
17                            19      7
4                             06      2
44                            50      2

[88 rows x 2 columns]

In [22]:
data_spheres = pd.read_excel('Data_spheres.xlsx')
data_spheres

         Code                                        Description
0          01  Բուսաբուծություն ու անասնաբուծություն, որսորդո...
1        01.1                  Ոչ բազմամյա մշակաբույսերի աճեցում
2       01.11  Հացահատիկային մշակաբույսերի (բացի բրնձից), հատ...
3     01.11.1  Հացահատիկային մշակաբույսերի (բացի բրնձից) աճեցում
4     01.11.2            Հատիկաընդեղենային մշակաբույսերի աճեցում
...       ...                                                ...
1587        U  Մասնավոր տնային տնտեսություններում ծառայությու...
1588       99     ՏԱՐԵՐԿՐՅԱ ԿԱԶՄԱԿԵՐՊՈՒԹՅՈՒՆՆԵՐԻ ԳՈՐԾՈՒՆԵՈՒԹՅՈՒՆ
1589     99.0    Օտարերկրյա կազմակերպությունների գործունեություն
1590    99.00    Օտարերկրյա կազմակերպությունների գործունեություն
1591  99.00.0    Օտարերկրյա կազմակերպությունների գործունեություն

[1592 rows x 2 columns]

In [23]:
merged_data = general_activity_counts.merge(data_spheres, left_on='Ընդանուր Գործունեության տեսակ', right_on='Code', how='left')

merged_data.loc[merged_data['Code'] == '01']

,Ընդանուր Գործունեության տեսակ,Count,Code,Description
19,01,1638,01,"Բուսաբուծություն ու անասնաբուծություն, որսորդո..."